### ISSUE TITLE
Stale entry causes "partially online"

### ISSUE THREAD

**Issue by jbree** [amiantos/pibar#10]
Awesome job on this project!

I clicked add/remove a few times before I figured out that I need to "Test" before I can save my entry.

After I successfully added, PiBar reported "Partially Offline", as the menu bar apparently had different thoughts about which Pi-holes it was responsible for. Here's a screenshot that shows the preferences along with the confused menu.

![Screen Shot 2020-05-22 at 2 06 17 PM](https://user-images.githubusercontent.com/6645643/82709519-a1349900-9c35-11ea-8a5f-b3c395c059ac.png)

Non-critical issue, went away after I quit and re-launched PiBar.

**Comment by amiantos** [comment]
Hi! Yeah, this has been reported before, but thanks for letting me know! Sad it made it into the release, but luckily the fix isn't a big deal. Will be fixed in 1.1.

I'll also figure out a better way to design the "add pi-hole" process to make it less confusing.

Main issue here: https://github.com/amiantos/pibar/issues/7
